import React from "react";
import { ChevronLeft ,ChevronsLeft, ChevronRight,ChevronsRight} from "lucide-react";

const SizesPagination = () => {
    return (
        <React.Fragment>
            <div className="card">
                <div className="card-body">
                    <h6 className="mb-4 text-15">Sizes</h6>

                    <div className="grid grid-cols-1 gap-5 xl:grid-cols-2">

                        <div>
                            <ul className="flex flex-wrap items-center gap-2 mb-3">
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-6 transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto"><ChevronLeft className="size-4 rtl:rotate-180" /></a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-6 transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">1</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-6 transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">2</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-6 transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">3</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-6 transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">4</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-6 transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto active">5</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-6 transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">6</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-6 transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto"><ChevronRight className="size-4 rtl:rotate-180" /></a>
                                </li>
                            </ul>
                            <ul className="flex flex-wrap items-center gap-2 mb-3">
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-8 transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto"><ChevronLeft className="size-4 rtl:rotate-180" /></a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-8 transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">1</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-8 transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto active">2</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-8 transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">3</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-8 transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">4</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-8 transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">5</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-8 transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">6</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-8 transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto"><ChevronRight className="size-4 rtl:rotate-180" /></a>
                                </li>
                            </ul>
                            <ul className="flex flex-wrap items-center gap-2">
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-10 text-lg transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto"><ChevronLeft className="size-4 rtl:rotate-180" /></a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-10 text-lg transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">1</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-10 text-lg transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">2</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-10 text-lg transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto active">3</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-10 text-lg transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">4</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-10 text-lg transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">5</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-10 text-lg transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">6</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-10 text-lg transition-all duration-150 ease-linear rounded text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 [&.active]:text-fecustom-500 dark:[&.active]:text-fecustom-500 [&.active]:hover:text-fecustom-700 dark:[&.active]:hover:text-fecustom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto"><ChevronRight className="size-4 rtl:rotate-180" /></a>
                                </li>
                            </ul>
                        </div>

                        <div>
                            <ul className="flex flex-wrap items-center gap-2 mb-3">
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-6 text-xs transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto"><ChevronsLeft className="size-3" /></a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-6 text-xs transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto"><ChevronLeft className="size-3" /></a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-6 text-xs transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">1</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-6 text-xs transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto active">2</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-6 text-xs transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">3</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-6 text-xs transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">4</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-6 text-xs transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">5</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-6 text-xs transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">6</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-6 text-xs transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto"><ChevronRight className="size-3" /></a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-6 text-xs transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto"><ChevronsRight className="size-3" /></a>
                                </li>
                            </ul>
                            <ul className="flex flex-wrap items-center gap-2 mb-3">
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-8 transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto"><ChevronsLeft className="size-4 rtl:rotate-180" /></a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-8 transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto"><ChevronLeft className="size-4 rtl:rotate-180" /></a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-8 transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">1</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-8 transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">2</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-8 transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">3</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-8 transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">4</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-8 transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto active">5</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-8 transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">6</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-8 transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto"><ChevronRight className="size-4 rtl:rotate-180" /></a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-8 transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto"><ChevronsRight className="size-4 rtl:rotate-180" /></a>
                                </li>
                            </ul>
                            <ul className="flex flex-wrap items-center gap-2">
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-10 text-lg transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto"><ChevronsLeft className="size-4 rtl:rotate-180" /></a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-10 text-lg transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto"><ChevronLeft className="size-4 rtl:rotate-180" /></a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-10 text-lg transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">1</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-10 text-lg transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto active">2</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-10 text-lg transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">3</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-10 text-lg transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">4</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-10 text-lg transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">5</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-10 text-lg transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto">6</a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-10 text-lg transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto"><ChevronRight className="size-4 rtl:rotate-180" /></a>
                                </li>
                                <li>
                                    <a href="#!" className="inline-flex items-center justify-center bg-white dark:bg-zinc-700 size-10 text-lg transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zinc-500 text-slate-500 dark:text-zinc-200 hover:text-fecustom-500 dark:hover:text-fecustom-500 hover:bg-fecustom-50 dark:hover:bg-fecustom-500/10 focus:bg-fecustom-50 dark:focus:bg-fecustom-500/10 focus:text-fecustom-500 dark:focus:text-fecustom-500 [&.active]:text-fecustom-50 dark:[&.active]:text-fecustom-50 [&.active]:bg-fecustom-500 dark:[&.active]:bg-fecustom-500 [&.active]:border-fecustom-500 dark:[&.active]:border-fecustom-500 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zinc-300 [&.disabled]:cursor-auto"><ChevronsRight className="size-4 rtl:rotate-180" /></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </React.Fragment>
    );
}

export default SizesPagination;