name: Frontend CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - uat

env:
  REGISTRY: docker.io

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fe:uat
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Copy docker-compose to remote
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          source: "docker-compose.yml,Caddyfile"
          target: "/root/Hosting-Manager"
          overwrite: true

      - name: Restart remote docker compose
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            set -e
            mkdir -p /root/Hosting-Manager
            cd /root/Hosting-Manager
            docker-compose down || true
            docker-compose pull
            docker-compose up -d
